language: java
script: mvn clean install
jdk:
- openjdk8
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis/deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: NJe4DI40lwrY/CmjGnhA7mVZhHSi0Xt7TwSPnsFFd3J+vg2Ja08dCq7vfpXkzaH/59it+lQWfa0zrQqxxi9KaxR+TrM3gyFvcHl24Y9A/UqML5DBz3ZnCuak135pWqonFew7JTooO0aNzLoE289+5lcT4LcPUHJhM3B7NA48O7jWpneK38kB2jv5lSd139+4GwPrwmk2i2K+0x/jDcqEBzZbP0pyRk3iAYra7oD1k8TLoUrSuspG5m6/39A+PjkSaM+u0blaG0o7lGTZxqO50b+Zjo4sXRrBIumAuy2YYgAVrYzgYsJAzYvSTUgJgKeF16WJkQlq1gpU/K/1vhak4H0bPc4rqdo/gXVZlfpF+bJ8y9Gh/HLjUDJNOrfNbVgBiI0K7vv+nAnzi/DyJrH/NqzK/6juA+eQZsGYG2Y+/oxH9IcAh7hvCKgbE3QJEZ8FpExX4qmQ7NMKdCXluzXQZvHzrWn/yZwHJ95H0pRLFP2lAbYD2but+6iz3d5u0gecRLFp9MAVz4mkNS/lnz8Dejd2BK+sZbDDVlISfRb1NHG1IVh44XQUlBsZ5/or98rH1x0jPgpDjPtfrHj/YM54fD24UnYhPMdmo9wHpoeCuw2p8fZ880SYikDr6x47FbUT9fmTRTE42j51bB+Kf14e+gEWf49tbwKRtVnDJ4//DWg=
  - secure: hdBfjUr/y51uSyp+OqWPiFNAg6Rs195wQ1nr7BXF0eN2B9iLSYLdKFLrLjfzRdkkHMBvK/MRqMz+wM36FBKCVQb6qRCmliWDdB46GaTJ3cWmElVu9ldKG9AgCUEJmuwxu/Fn6u81jiFJLs98LbUIxpeb/3XgcOiDrZllvl5Omsk31hKJdjhPcYVChsncmubC7JyXZAq6NW9VkvJn1dNtucoA0OzracGSI0afaHy6FfUehWkD0+qDZ0DLbFml7UDFApEvKKZWvqt+SapedAJy4Lx8nwxkHO85LZGz6DFKzJb1YuZiotih6Ft1cFiPxhL0VZqZKDQHtauYGEpN2qf3T/tcHmjkFMuOd8LWi9fG0K+Lw1HsWD9P48jtk1Y40y7eXxVmlSJUkejoCngeOv/rvs8tT9piD2n7xEySeT8F6mQglr/drcG1izJyiFrV4VpGTtpnZGD2HI0YqnHarICpF8q5c99RHvuj+No6YHMhkbD2NZoyybGSStz+3GxqaW/xILvIahZ6rWfcm9J7W/ZGgCxi8/wNvV5YHtdiVeO59KtL5+wwWMoBejoeflcKa/JS7sRYI/MlrQglyxEGhzthcEFaj5QCwjl/ctTnUuiyQyX59j3PU/yDmgpdQhHEWHUJtVdJwtoUa9FHaDrdElc2vlKAQWr80XtGOoaCTgLBBdc=
before_install:
- openssl aes-256-cbc -K $encrypted_a973f24e4f75_key -iv $encrypted_a973f24e4f75_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
