language: java
script: mvn clean install
jdk:
- openjdk8
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis/deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: YRRAwqk3z4fYQ4ELBy7k/rZ6m6+u28781h0mAncRnpokv7GdrP5Nn0YmV0EMlSgxxsYRqdE0exFkXWLKCNLKnhmFKh59h8cBEbAO9CxsiRgSZnivUbDZD6s9wnySFEUaApm6WVPWhKgoqKSKuyCMANpB4yU4xphLiA2mpf9SmkTVbYKnuNmxC2yfgOWGY+Q5k+guh1yxdw+oGGbsYl86BfipqvNQjyhxc1v13ioMtv2fLtcFOVCtBIB2qDaWM2oXuDlbjL2VReCTa9DX1VaujOlFB/+CDopplbgj/5gcp/oBaWSZsurD5ADtpx/BvI1mCFZ6bIliMgXWvA4qzlL/iVdk2BoZvMYDlnpGiVqD1E8D8qQvdTfdsS21jpj5ZC+0Z7jz4JOU6Kmsw8Cds49rWxlTmoeaVMxU7NMnpnJOp6Ur/lOD4WWqN5gNu9AYy+W1shb2kUHctaoBAJiiRpLvFALKjCpzCNiGpj/nvCsrcl7Wuxx8k8rFYmlQJTRiyaLzPOZcIRQoIYfAQI+F/tNlePgjs91PquLXeQ2Gk3Ux9d3QXXFu6dD3ZWqn6xkTFXoX48a7FgdGjDvxNOOdEn/uSgiZdIZoCpJ/OgRoSQGD3++1UbBVHmglg+NERr+kqYPVmrj7TQYEUkYQABPt/xEprL5HMFcC7TwPo3nOR95obmg=
  - secure: XpWUcTew3K/a55fmk1tmO5oKHywtSZ8BlH0LTrgNjkWs/DVJyat3F5aRP4Obk51Oy5GFApDxQbknM5wmgheduEb6OWMaA64drPn283pi27P+auMpm73zeaIA458j6FnyTcVD4cQMufjN6EASkVc6HP6V6+oX7wssKrHPTbpfzPG3VJM+WkZXLJNzjtdzcQ7WuRyvbNNkVfW5yPDf9S2Dw7x9RkpWg7tVZjXKjVoWeoBhSi9nIMXxyDa1O4MO88408y+xbxSj3fNtNewOhUnwTU/f/fiAGlLXyGodlU05jh0Gu1RxnrLP8P2WgW/71J+aIrCH6v+d/p1z+AvV2s5gyGufSmJPzdte9N3kPCNOcsVVERhwzKHmPuwQc9jIfn+7QGcReaS5yMpjeXXtURWDOCWtS94MMI8t3fYAxP5nCbc2JVqWg7tFXRD/6vHHFf/nifdY7YXZ/Kr79DF3zv/m3hRrRR5/c6+JMemUbmrgbWLrqqN5Q/8X92DRH5Ah4XxgeqYWyxK/WEm+WiPJ6mh3rfiqIdvps3HwnKo6BNINdrF7VlLEVWOhBGRO00Ek2YBERQyZQfKBHj6JPqtXv9lD2CxztvnoktNhgzx5SkScZWCObFziO712Yaa6S0XB4Mv3mQynFkFdQGd0RgWBzGTtj4QV2Pj1JXh0FodtGWNHZKg=
before_install:
- openssl aes-256-cbc -K $encrypted_a973f24e4f75_key -iv $encrypted_a973f24e4f75_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
